### ISSUE TITLE
Account Tab

### ISSUE THREAD

**Issue by jlau87** [outsider787/edd6-Construkted#10]
As an unregistered user, when opening the drop down menu for the accounts tab, the options are Your Membership, Edit Profile, and Update Billing Card.

Perhaps Edit Profile and Update Billing Card should not appear for unregistered users?

Going into Your Membership, brings up a page where you are able to log in but you are not able to sign up for a new membership.

![Screen Shot 2019-09-15 at 8 27 48 PM](https://user-images.githubusercontent.com/54898487/64930219-b03c8f00-d7fc-11e9-8607-0132ca9cabc8.png)

Going into Update Billing Card brings up a blank page
![Screen Shot 2019-09-15 at 8 28 06 PM](https://user-images.githubusercontent.com/54898487/64930220-b03c8f00-d7fc-11e9-8f9e-8384ca6fb6e1.png)

**Comment by outsider787** [comment]
Those menu options are no longer available to users that are not logged-in.
