### ISSUE TITLE
Your store url: ... (does not direct correctly)

### ISSUE THREAD

**Issue by jlau87** [outsider787/edd6-Construkted#14]
From the user dashboard page, this link:
![Screen Shot 2019-09-25 at 2 33 12 PM](https://user-images.githubusercontent.com/54898487/65630578-b7edf780-dfa3-11e9-9d86-3501b0bf8ff9.png)

Leads to this page:
![Screen Shot 2019-09-25 at 2 33 46 PM](https://user-images.githubusercontent.com/54898487/65630621-c9cf9a80-dfa3-11e9-93ca-ca0e1552389b.png)
![Screen Shot 2019-09-25 at 2 45 36 PM](https://user-images.githubusercontent.com/54898487/65630622-c9cf9a80-dfa3-11e9-88ac-8f37330db78f.png)

**Comment by jlau87** [comment]
http://edd8.construkted.com/gallery/jason-lau-test-account-4/?author_downloads=true

**Comment by outsider787** [comment]
There is something weird with that account.
That link (with a different user name) does not bring up that extra data.

Since the users have been wiped by the recent website update, keep an eye out for this happening again.
