### ISSUE TITLE
User Dashboard Formatting

### ISSUE THREAD

**Issue by jlau87** [outsider787/edd6-Construkted#9]
As an unregistered user, the User Dashboard is not formatted correctly. (When signed in, this issue does not occur)

![Screen Shot 2019-09-15 at 8 25 20 PM](https://user-images.githubusercontent.com/54898487/64930145-d4e43700-d7fb-11e9-8a63-b7c9ee268e44.png)

**Comment by outsider787** [comment]
good point.
I've seen that incorrect formatting before, but was never sure how I got to it.

**Comment by outsider787** [comment]
Problem solved.
"Account" menu now only visible to logged-in users
